### ISSUE TITLE
Code Contribution 

### ISSUE THREAD

**Issue by aayushi-droid** [sahu-mak/Data-Science-Portfolio#2]
can i add logistic regression code?

**Comment by sahu-mak** [comment]
hello aayushi, sorry I am new to github. Haven't got to used to the working exactly. But if I am correct you want to add code to my repo right?

**Comment by aayushi-droid** [comment]
Hi  Sahu-mak, Yes You are correct, I gave You Pull request check code and Pull them in Your Repository.
For github fork workflow check : https://gist.github.com/Chaser324/ce0505fbed06b947d962
Or you can do with Simpy going to Pull Request.

**Comment by sahu-mak** [comment]
I appreciate you adding your code. But the repo data science portfolio i meant to be used by me for applying for jobs. I think it will inappropriate on my part if someone else contribute in that repo. So i would like you to please consider another repo which I created called projects. Thank you for your consideration. :-)

**Comment by aayushi-droid** [comment]
##### Yes, I can understand. Acctually i was also creating contribution to open-source projects for My portfolio. I will Consider another Repo. Thanks
